// <auto-generated />
using AccuLynxCodeTest.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccuLynxCodeTest.Migrations.AnswersDbMigrations
{
    [DbContext(typeof(AnswersDb))]
    partial class AnswersDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccuLynxCodeTest.Models.AnswerModel", b =>
                {
                    b.Property<int>("answer_id");

                    b.Property<string>("body");

                    b.Property<int>("creation_date");

                    b.Property<int>("question_id");

                    b.Property<string>("share_link");

                    b.Property<string>("title");

                    b.HasKey("answer_id");

                    b.ToTable("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
